const timeEl = document.getElementById('time')
const AM_PM_EL = document.getElementById('am-pm')
const date= document.getElementById('date')
const timeZoneEl = document.getElementById('timeZone')
const cordinatesEl = document.getElementById('cordinates')
const currentDay = document.getElementById('monday')
